export interface Plant {
    id: number;
    nombre: string;
    precio: number;
    categoria: string;
    ocasion: string[];
    imagen: string;
    popular?: boolean;
}

export const plants: Plant[] = [
    // 1. Aniversario
    {
        id: 1,
        nombre: "Amor Eterno",
        precio: 180,
        categoria: "Aniversario",
        ocasion: ["amor", "aniversario"],
        imagen: "/img/img-catalogo/C-Aniversario.jpg",
        popular: true,
    },
    {
        id: 2,
        nombre: "Dulce Compañía",
        precio: 150,
        categoria: "Aniversario",
        ocasion: ["amor", "aniversario"],
        imagen: "/img/img-tarjeta/f1.jpg",
        popular: false,
    },
    {
        id: 3,
        nombre: "Promesa de Amor",
        precio: 120,
        categoria: "Aniversario",
        ocasion: ["amor", "aniversario"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: false,
    },

    // 2. Arreglos en Caja
    {
        id: 4,
        nombre: "Caja Sorpresa Rosa",
        precio: 140,
        categoria: "Arreglos en Caja",
        ocasion: ["cumpleaños", "amor"],
        imagen: "/img/img-catalogo/C-Arregloscaja.jpg",
        popular: true,
    },
    {
        id: 5,
        nombre: "Box de Lujo Mix",
        precio: 160,
        categoria: "Arreglos en Caja",
        ocasion: ["aniversario", "cumpleaños"],
        imagen: "/img/img-tarjeta/f6.jpg",
        popular: true,
    },
    {
        id: 6,
        nombre: "Caja Corazón Rojo",
        precio: 130,
        categoria: "Arreglos en Caja",
        ocasion: ["amor"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: false,
    },

    // 3. Bodas
    {
        id: 7,
        nombre: "Ramo de Novia Imperial",
        precio: 250,
        categoria: "Bodas",
        ocasion: ["boda"],
        imagen: "/img/img-catalogo/C-Bodas.jpg",
        popular: true,
    },
    {
        id: 8,
        nombre: "Centro de Mesa Nupcial",
        precio: 190,
        categoria: "Bodas",
        ocasion: ["boda"],
        imagen: "/img/img-catalogo/C-Centrosdemesa.jpg",
        popular: false,
    },
    {
        id: 9,
        nombre: "Arreglo Altar Pureza",
        precio: 300,
        categoria: "Bodas",
        ocasion: ["boda"],
        imagen: "/img/img-catalogo/C-Ramospremium.jpg",
        popular: true,
    },

    // 4. Centros de Mesa
    {
        id: 10,
        nombre: "Centro de Mesa Elegancia",
        precio: 120,
        categoria: "Centros de Mesa",
        ocasion: ["cena", "evento"],
        imagen: "/img/img-catalogo/C-Centrosdemesa.jpg",
        popular: false,
    },
    {
        id: 11,
        nombre: "Mesa Festiva Tropical",
        precio: 95,
        categoria: "Centros de Mesa",
        ocasion: ["cumpleaños"],
        imagen: "/img/img-tarjeta/f4.jpg",
        popular: false,
    },
    {
        id: 12,
        nombre: "Centro Floral Navideño",
        precio: 110,
        categoria: "Centros de Mesa",
        ocasion: ["festividad"],
        imagen: "/img/img-tarjeta/f10.jpg",
        popular: false,
    },

    // 5. Condolencias
    {
        id: 13,
        nombre: "Corona de Paz",
        precio: 220,
        categoria: "Condolencias",
        ocasion: ["condolencias"],
        imagen: "/img/img-catalogo/C-Condolencias.jpg",
        popular: false,
    },
    {
        id: 14,
        nombre: "Lágrimas Blancas",
        precio: 150,
        categoria: "Condolencias",
        ocasion: ["condolencias"],
        imagen: "/img/img-tarjeta/f2.jpg",
        popular: false,
    },
    {
        id: 15,
        nombre: "Cruz de Rosas",
        precio: 280,
        categoria: "Condolencias",
        ocasion: ["condolencias"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: false,
    },

    // 6. Cumpleaños
    {
        id: 16,
        nombre: "Fiesta de Colores",
        precio: 95,
        categoria: "Cumpleaños",
        ocasion: ["cumpleaños"],
        imagen: "/img/img-catalogo/C-Cumpleaños.jpg",
        popular: true,
    },
    {
        id: 17,
        nombre: "Feliz Día Sunshine",
        precio: 85,
        categoria: "Cumpleaños",
        ocasion: ["cumpleaños"],
        imagen: "/img/img-catalogo/C-Girasoles.jpg",
        popular: true,
    },
    {
        id: 18,
        nombre: "Globo y Flores Pack",
        precio: 110,
        categoria: "Cumpleaños",
        ocasion: ["cumpleaños"],
        imagen: "/img/img-tarjeta/f8.jpg",
        popular: false,
    },

    // 7. Día del Padre
    {
        id: 19,
        nombre: "Caballero Azul",
        precio: 120,
        categoria: "Día del Padre",
        ocasion: ["dia del padre"],
        imagen: "/img/img-catalogo/C-DiadelPadre.jpg",
        popular: false,
    },
    {
        id: 20,
        nombre: "Detalle Papá",
        precio: 90,
        categoria: "Día del Padre",
        ocasion: ["dia del padre"],
        imagen: "/img/img-catalogo/C-Ramosdemano.jpg",
        popular: false,
    },
    {
        id: 21,
        nombre: "Box Papá Especial",
        precio: 150,
        categoria: "Día del Padre",
        ocasion: ["dia del padre"],
        imagen: "/img/img-catalogo/C-Arregloscaja.jpg",
        popular: false,
    },

    // 8. Día de la Madre
    {
        id: 22,
        nombre: "Reina de la Casa",
        precio: 180,
        categoria: "Día de la Madre",
        ocasion: ["dia de la madre"],
        imagen: "/img/img-catalogo/C-DiadelaMadre.jpg",
        popular: true,
    },
    {
        id: 23,
        nombre: "Mamá Te Amo",
        precio: 140,
        categoria: "Día de la Madre",
        ocasion: ["dia de la madre"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: true,
    },
    {
        id: 24,
        nombre: "Tulipanes para Mamá",
        precio: 130,
        categoria: "Día de la Madre",
        ocasion: ["dia de la madre"],
        imagen: "/img/img-catalogo/C-Tulipanes.jpg",
        popular: true,
    },

    // 9. Girasoles
    {
        id: 25,
        nombre: "Rayo de Sol",
        precio: 80,
        categoria: "Girasoles",
        ocasion: ["amistad", "cumpleaños"],
        imagen: "/img/img-catalogo/C-Girasoles.jpg",
        popular: true,
    },
    {
        id: 26,
        nombre: "Jardín de Girasoles",
        precio: 120,
        categoria: "Girasoles",
        ocasion: ["aniversario"],
        imagen: "/img/img-catalogo/C-Ramosdemano.jpg",
        popular: false,
    },
    {
        id: 27,
        nombre: "Girasoles y Rosas",
        precio: 110,
        categoria: "Girasoles",
        ocasion: ["amor"],
        imagen: "/img/img-tarjeta/f3.jpg",
        popular: true,
    },

    // 10. Graduaciones
    {
        id: 28,
        nombre: "Logro Académico",
        precio: 100,
        categoria: "Graduaciones",
        ocasion: ["graduacion"],
        imagen: "/img/img-catalogo/C-Graduaciones.jpg",
        popular: false,
    },
    {
        id: 29,
        nombre: "Felicidades Graduado",
        precio: 130,
        categoria: "Graduaciones",
        ocasion: ["graduacion"],
        imagen: "/img/img-catalogo/C-Ramospremium.jpg",
        popular: false,
    },
    {
        id: 30,
        nombre: "Pack Graduación",
        precio: 150,
        categoria: "Graduaciones",
        ocasion: ["graduacion"],
        imagen: "/img/img-catalogo/C-Arregloscaja.jpg",
        popular: false,
    },

    // 11. Orquídeas
    {
        id: 31,
        nombre: "Orquídea Phalaenopsis",
        precio: 160,
        categoria: "Orquídeas",
        ocasion: ["elegancia", "oficina"],
        imagen: "/img/img-catalogo/C-Orquideas.jpg",
        popular: true,
    },
    {
        id: 32,
        nombre: "Orquídea Doble Vara",
        precio: 200,
        categoria: "Orquídeas",
        ocasion: ["lujo"],
        imagen: "/img/img-tarjeta/f10.jpg",
        popular: false,
    },
    {
        id: 33,
        nombre: "Orquídea Mini Púrpura",
        precio: 90,
        categoria: "Orquídeas",
        ocasion: ["detalle"],
        imagen: "/img/img-catalogo/C-Orquideas.jpg",
        popular: false,
    },

    // 12. Ramos de Mano
    {
        id: 34,
        nombre: "Ramo Silvestre",
        precio: 70,
        categoria: "Ramos de Mano",
        ocasion: ["casual"],
        imagen: "/img/img-catalogo/C-Ramosdemano.jpg",
        popular: false,
    },
    {
        id: 35,
        nombre: "Mix de Estación",
        precio: 60,
        categoria: "Ramos de Mano",
        ocasion: ["agradecimiento"],
        imagen: "/img/img-tarjeta/f8.jpg",
        popular: true,
    },
    {
        id: 36,
        nombre: "Ramo Pastel",
        precio: 75,
        categoria: "Ramos de Mano",
        ocasion: ["nacimiento"],
        imagen: "/img/img-tarjeta/f1.jpg",
        popular: false,
    },

    // 13. Ramos Premium
    {
        id: 37,
        nombre: "Gran Lujo Floral",
        precio: 350,
        categoria: "Ramos Premium",
        ocasion: ["aniversario", "boda"],
        imagen: "/img/img-catalogo/C-Ramospremium.jpg",
        popular: true,
    },
    {
        id: 38,
        nombre: "Elegancia Absoluta",
        precio: 280,
        categoria: "Ramos Premium",
        ocasion: ["compromiso"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: true,
    },
    {
        id: 39,
        nombre: "Premium Mix 100",
        precio: 400,
        categoria: "Ramos Premium",
        ocasion: ["evento"],
        imagen: "/img/img-catalogo/C-Bodas.jpg",
        popular: true,
    },

    // 14. Rosas
    {
        id: 40,
        nombre: "24 Rosas Rojas",
        precio: 140,
        categoria: "Rosas",
        ocasion: ["amor"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: true,
    },
    {
        id: 41,
        nombre: "Bouquet Rosas Blancas",
        precio: 130,
        categoria: "Rosas",
        ocasion: ["paz", "boda"],
        imagen: "/img/img-tarjeta/f2.jpg",
        popular: false,
    },
    {
        id: 42,
        nombre: "Rosas y Chocolates",
        precio: 160,
        categoria: "Rosas",
        ocasion: ["amor", "aniversario"],
        imagen: "/img/img-tarjeta/f6.jpg",
        popular: true,
    },

    // 15. San Valentín
    {
        id: 43,
        nombre: "Cupido Pack",
        precio: 200,
        categoria: "San Valentín",
        ocasion: ["san valentín"],
        imagen: "/img/img-catalogo/C-Sanvalentin.jpg",
        popular: true,
    },
    {
        id: 44,
        nombre: "Te Amo Gigante",
        precio: 250,
        categoria: "San Valentín",
        ocasion: ["san valentín"],
        imagen: "/img/img-catalogo/C-Rosas.jpg",
        popular: true,
    },
    {
        id: 45,
        nombre: "Dulce San Valentín",
        precio: 120,
        categoria: "San Valentín",
        ocasion: ["san valentín"],
        imagen: "/img/img-catalogo/C-Arregloscaja.jpg",
        popular: true,
    },

    // 16. Tulipanes
    {
        id: 46,
        nombre: "10 Tulipanes Rojos",
        precio: 90,
        categoria: "Tulipanes",
        ocasion: ["amor"],
        imagen: "/img/img-catalogo/C-Tulipanes.jpg",
        popular: true,
    },
    {
        id: 47,
        nombre: "Tulipanes Multicolores",
        precio: 95,
        categoria: "Tulipanes",
        ocasion: ["amistad", "cumpleaños"],
        imagen: "/img/img-tarjeta/f8.jpg",
        popular: true,
    },
    {
        id: 48,
        nombre: "Tulipanes Amarillos",
        precio: 90,
        categoria: "Tulipanes",
        ocasion: ["amistad"],
        imagen: "/img/img-tarjeta/f3.jpg",
        popular: false,
    }
];
